SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE users RESTART IDENTITY;
TRUNCATE TABLE authors RESTART IDENTITY;
TRUNCATE TABLE books RESTART IDENTITY;
TRUNCATE TABLE genres RESTART IDENTITY;
TRUNCATE TABLE genre_book RESTART IDENTITY;
TRUNCATE TABLE loans RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;